version: '3.9'  # Docker Engine release 19.03.0+ [https://docs.docker.com/compose/compose-file/]

services: 

    # setup MongoDB cluster for production
    mongo-replica-setup:
        container_name: mongo-setup
        image: 'mongo:4.2'
        restart: on-failure
        networks:
            - my-net2
        volumes:
        - ./mongosetup.sh:/scripts/mongosetup.sh
        depends_on:
        - mongo1
        - mongo2
        - mongo3

    mongo1:
        hostname: 'mongo1'
        container_name: 'mongo1'
        image: 'mongo:4.2'
        restart: 'on-failure'
        command: ["--replSet", "myrs"]
        expose: 
            - 27017
        ports: 
            - 28017:27017 
        networks: 
            - my-net2
        volumes:
            - flv1,destination=/data/db

    mongo2:
        hostname: 'mongo2'
        container_name: 'mongo2'
        image: 'mongo:4.2'
        restart: 'on-failure'
        command: ["--replSet", "myrs"]
        expose: 
            - 27017
        ports: 
            - 28018:27017 
        networks: 
            - my-net2
        volumes:
            - flv2,destination=/data/db

    mongo3:
        hostname: 'mongo3'
        container_name: 'mongo3'
        image: 'mongo:4.2'
        restart: 'on-failure'
        command: ["--replSet", "myrs"]
        expose: 
            - 27017
        ports: 
            - 28019:27017 
        networks: 
            - my-net2
        volumes:
            - flv3,destination=/data/db


volumes: 
    fmv1:
    fmv2:
    fmv3:

networks: 
    my-net2:
