version: '3'

services: 

    rabbitmq:
        container_name: rabbitmq
        hostname: rabbitmq
        image: rabbitmq:3-management
        ports:
          - '8080:15672'
        environment:
          - RABBITMQ_DEFAULT_USER=rmq
          - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASS}
          - RABBITMQ_DEFAULT_VHOST=my_vhost
          
